[[language]]
name = "python"
language-servers = [ "pylsp" ]
# auto-format = true

[[language]]
name = "java"
indent = { tab-width = 4, unit = "    " }

[language.debugger]
name = "jdb"
command = "jdb"
port-arg = "--port {}"
transport = "tcp"

[[language.debugger.templates]]
name = "attach"
request = "attach"
completion = [ "pid" ]
args = { pid = "{0}" }

[language-server.pylsp.config.pylsp.plugins]
ruff.enabled = true
autopep8.enabled = false
flake8.enabled = true
mccabe.enabled = false
pycodestyle.enabled = false
pyflakes.enabled = false
pylint.enabled = true
yapf.enabled = false
